<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net45;netstandard2.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>Ping9719</Authors>
		<Description>这是一个工业通讯库Hid扩展库。包含不常用的通信方式（USB，蓝牙，串口）。
This is the Hid extension library for an industrial communication library. It includes less commonly used communication methods (USB, Bluetooth, serial port).

https://github.com/ping9719/IoT
https://gitee.com/ping9719/IoT</Description>
		<PackageProjectUrl>https://github.com/ping9719/IoT</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ping9719/IoT</RepositoryUrl>
		<Version>0.12.0</Version>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="HidSharp" Version="2.6.4" />
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net45" Version="1.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Ping9719.IoT\Ping9719.IoT.csproj" />
	</ItemGroup>

</Project>
